### ISSUE TITLE
Minification fails with razzle

### ISSUE THREAD

**Issue by jee1mr** [femioladeji/react-slideshow#41]
Command: `razzle build && NODE_ENV=production node build/server.js`
Error:
```
File sizes after gzip:

  234.98 KB  build/static/js/bundle.0ed89db1.js
  2.42 KB    build/static/css/bundle.242a7373.css

./node_modules/react-slideshow-image/lib/components/slideshow/general.css:1
(function (exports, require, module, __filename, __dirname) { .react-slideshow-container {
                                                              ^

SyntaxError: Unexpected token .
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by femioladeji** [comment]
Thanks for pointing it out @jee1mr. I'll investigate that and fix it asap

**Comment by kwminfinidea** [comment]
Same error when building with nextjs

Command: next build
Error:

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18) type: 'SyntaxError', '$error': '$error' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by femioladeji** [comment]
Hi @kwminfinidea I've not had enough time to investigate the issue properly. For nextjs can you check this sandbox https://codesandbox.io/s/slideshow-for-next-wj3gf? The `next build`` command works for it. Let me know if you're still having some issues

**Comment by jee1mr** [comment]
@femioladeji 
https://github.com/jaredpalmer/razzle/issues/692
This might be useful.

**Comment by cbeier** [comment]
@femioladeji I have cloned the sandbox and "next build" still produce the same error.

`> slideshow-for-next@1.0.0 build /Users/cbeier/Downloads/test
> next build

Creating an optimized production build  

Compiled successfully.

> Build error occurred
{ /Users/cbeier/Downloads/test/node_modules/react-slideshow-image/lib/components/slideshow/general.css:1
.react-slideshow-container {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/cbeier/Downloads/test/node_modules/react-slideshow-image/lib/index.js:25:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10) type: 'SyntaxError' }
Creating an optimized production build .Automatically optimizing pages .`

I did a little research and found the following:

- A comment that describes the problem well: https://github.com/aws-amplify/amplify-js/issues/3854
- [Next build crash when 3rd party CSS files are required.](https://spectrum.chat/next-js/general/next-build-crash-when-3rd-party-css-files-are-required~70daebac-88a4-40cc-9d8f-1447b3bbe3e5)

Unfortunately, I am not aware of any solution to the problem yet.

**Comment by femioladeji** [comment]
This error has been fixed now. please check the `nextjs` section of the readme for the new configuration
